---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-1.11
  - EMBER_TRY_SCENARIO=ember-1.12
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-2.0
  - EMBER_TRY_SCENARIO=ember-2.1
  - EMBER_TRY_SCENARIO=ember-2.2
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-2.6-ed-2.4
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-2.6-ed-2.5
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-2.6-ed-2.6
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-2.7-ed-2.6
  - ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-2.7-ed-2.7

matrix:
  fast_finish: true
  allow_failures:
   - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-2.7-ed-2.6
   - env: ALLOW_DEPRECATIONS=true EMBER_TRY_SCENARIO=ember-2.7-ed-2.7

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
